name: CD / Pack & Publish Todo.Core

permissions:
  packages: write
  contents: read

on:
  push:
    branches: [ master ]

jobs:
  pack-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Find Todo.Core csproj
        run: |
          PROJECT=$(find . -type f -name "Todo.Core.csproj" | head -n 1)
          if [ -z "$PROJECT" ]; then
            echo "ERROR: Todo.Core not found"
            exit 1
          fi
          echo "PROJECT_PATH=$PROJECT" >> $GITHUB_ENV

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release

      - name: Pack
        run: |
          VERSION="1.0.${{ github.run_number }}"
          dotnet pack ${{ env.PROJECT_PATH }} -c Release -o ./artifacts /p:PackageVersion=$VERSION

      - name: Create nuget.config
        run: |
          cat <<EOF > nuget.config
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <packageSources>
              <add key="github" value="https://nuget.pkg.github.com/Reshala5739/index.json" />
            </packageSources>
            <packageSourceCredentials>
              <github>
                <add key="Username" value="Reshala5739" />
                <add key="ClearTextPassword" value="${GH_PACKAGES_PAT}" />
              </github>
            </packageSourceCredentials>
          </configuration>
          EOF
        env:
          GH_PACKAGES_PAT: ${{ secrets.GH_PACKAGES_PAT }}

      - name: Push to GitHub Packages
        run: |
          dotnet nuget push ./artifacts/*.nupkg \
            --configfile nuget.config \
            --source "github" \
            --skip-duplicate \
            -v detailed